[package]
name = "depend"
version = "0.1.0"
authors = ["uHOOCCOOHu <hooccooh1896@gmail.com>"]

[lib]
name = "depend"
path = "src/lib.rs"

[dependencies]

[dependencies.clippy]
version = "*"
optional = true
